# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndvi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_frame.sizePolicy().hasHeightForWidth())
        self.tools_frame.setSizePolicy(sizePolicy)
        self.tools_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.tools_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tools_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tools_frame.setObjectName("tools_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tools_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadRGBBtn = QtWidgets.QPushButton(self.tools_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRGBBtn.sizePolicy().hasHeightForWidth())
        self.loadRGBBtn.setSizePolicy(sizePolicy)
        self.loadRGBBtn.setObjectName("loadRGBBtn")
        self.horizontalLayout_2.addWidget(self.loadRGBBtn)
        self.loadNDVIBtn = QtWidgets.QPushButton(self.tools_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadNDVIBtn.sizePolicy().hasHeightForWidth())
        self.loadNDVIBtn.setSizePolicy(sizePolicy)
        self.loadNDVIBtn.setObjectName("loadNDVIBtn")
        self.horizontalLayout_2.addWidget(self.loadNDVIBtn)
        self.selectBtn = QtWidgets.QPushButton(self.tools_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setObjectName("selectBtn")
        self.horizontalLayout_2.addWidget(self.selectBtn)
        self.opencvBtn = QtWidgets.QPushButton(self.tools_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opencvBtn.sizePolicy().hasHeightForWidth())
        self.opencvBtn.setSizePolicy(sizePolicy)
        self.opencvBtn.setObjectName("opencvBtn")
        self.horizontalLayout_2.addWidget(self.opencvBtn)
        self.verticalLayout.addWidget(self.tools_frame, 0, QtCore.Qt.AlignLeft)
        self.img_frame = QtWidgets.QFrame(self.centralwidget)
        self.img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_frame.setObjectName("img_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.img_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rgb_view = ImageViewer(self.img_frame)
        self.rgb_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rgb_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rgb_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.rgb_view.setBackgroundBrush(brush)
        self.rgb_view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.rgb_view.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.rgb_view.setObjectName("rgb_view")
        self.gridLayout.addWidget(self.rgb_view, 0, 0, 1, 1)
        self.ndvi_view = ImageViewer(self.img_frame)
        self.ndvi_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ndvi_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.ndvi_view.setBackgroundBrush(brush)
        self.ndvi_view.setObjectName("ndvi_view")
        self.gridLayout.addWidget(self.ndvi_view, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.img_frame)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NDVI Labeling"))
        self.loadRGBBtn.setText(_translate("MainWindow", "Cargar RGB"))
        self.loadNDVIBtn.setText(_translate("MainWindow", "Cargar NDVI"))
        self.selectBtn.setText(_translate("MainWindow", "Seleccionar"))
        self.opencvBtn.setText(_translate("MainWindow", "OpenCV"))

from ndvi_lib.ndvi_class import ImageViewer
