# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndvi_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.img_rgb_layout = QtWidgets.QVBoxLayout()
        self.img_rgb_layout.setObjectName("img_rgb_layout")
        self.rgb_tools = QtWidgets.QHBoxLayout()
        self.rgb_tools.setContentsMargins(0, 0, 0, 0)
        self.rgb_tools.setSpacing(6)
        self.rgb_tools.setObjectName("rgb_tools")
        self.loadRGBBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRGBBtn.sizePolicy().hasHeightForWidth())
        self.loadRGBBtn.setSizePolicy(sizePolicy)
        self.loadRGBBtn.setObjectName("loadRGBBtn")
        self.rgb_tools.addWidget(self.loadRGBBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rgb_tools.addItem(spacerItem)
        self.img_rgb_layout.addLayout(self.rgb_tools)
        self.rgb_view = RGBViewer(self.centralwidget)
        self.rgb_view.setFrameShape(QtWidgets.QFrame.Box)
        self.rgb_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rgb_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.rgb_view.setBackgroundBrush(brush)
        self.rgb_view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.rgb_view.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.rgb_view.setObjectName("rgb_view")
        self.img_rgb_layout.addWidget(self.rgb_view)
        self.rgb_info = QtWidgets.QLabel(self.centralwidget)
        self.rgb_info.setText("")
        self.rgb_info.setObjectName("rgb_info")
        self.img_rgb_layout.addWidget(self.rgb_info)
        self.main_layout.addLayout(self.img_rgb_layout)
        self.img_ndvi_layout = QtWidgets.QVBoxLayout()
        self.img_ndvi_layout.setObjectName("img_ndvi_layout")
        self.ndvi_tools = QtWidgets.QHBoxLayout()
        self.ndvi_tools.setContentsMargins(0, 0, 0, 0)
        self.ndvi_tools.setObjectName("ndvi_tools")
        self.loadNDVIBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadNDVIBtn.sizePolicy().hasHeightForWidth())
        self.loadNDVIBtn.setSizePolicy(sizePolicy)
        self.loadNDVIBtn.setObjectName("loadNDVIBtn")
        self.ndvi_tools.addWidget(self.loadNDVIBtn)
        self.selectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setObjectName("selectBtn")
        self.ndvi_tools.addWidget(self.selectBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ndvi_tools.addItem(spacerItem1)
        self.img_ndvi_layout.addLayout(self.ndvi_tools)
        self.ndvi_view = NDVIViewer(self.centralwidget)
        self.ndvi_view.setFrameShape(QtWidgets.QFrame.Box)
        self.ndvi_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ndvi_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.ndvi_view.setBackgroundBrush(brush)
        self.ndvi_view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.ndvi_view.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.ndvi_view.setObjectName("ndvi_view")
        self.img_ndvi_layout.addWidget(self.ndvi_view)
        self.ndvi_info = QtWidgets.QLabel(self.centralwidget)
        self.ndvi_info.setText("")
        self.ndvi_info.setObjectName("ndvi_info")
        self.img_ndvi_layout.addWidget(self.ndvi_info)
        self.main_layout.addLayout(self.img_ndvi_layout)
        self.gridLayout_2.addLayout(self.main_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 947, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menuBar)
        self.menuEditar.setObjectName("menuEditar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbrir_imagen_RGB = QtWidgets.QAction(MainWindow)
        self.actionAbrir_imagen_RGB.setObjectName("actionAbrir_imagen_RGB")
        self.actionAbrir_imagen_NDVI = QtWidgets.QAction(MainWindow)
        self.actionAbrir_imagen_NDVI.setObjectName("actionAbrir_imagen_NDVI")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setEnabled(False)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_como = QtWidgets.QAction(MainWindow)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSeleccionar = QtWidgets.QAction(MainWindow)
        self.actionSeleccionar.setObjectName("actionSeleccionar")
        self.menuArchivo.addAction(self.actionAbrir_imagen_RGB)
        self.menuArchivo.addAction(self.actionAbrir_imagen_NDVI)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_como)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionSeleccionar)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuEditar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NDVI Labeling"))
        self.loadRGBBtn.setText(_translate("MainWindow", "Cargar RGB"))
        self.loadNDVIBtn.setText(_translate("MainWindow", "Cargar NDVI"))
        self.selectBtn.setText(_translate("MainWindow", "Seleccionar"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.actionAbrir_imagen_RGB.setText(_translate("MainWindow", "Abrir imagen RGB"))
        self.actionAbrir_imagen_NDVI.setText(_translate("MainWindow", "Abrir imagen NDVI"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como..."))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSeleccionar.setText(_translate("MainWindow", "Seleccionar"))

from ndvi_lib.ndvi_class import NDVIViewer, RGBViewer
